require("montage-testing").run(require,[
    // Please keep in alphabetical order
    "test/anchor/anchor-spec",
    "test/autocomplete/autocomplete-spec",
    "test/blueprint/button/button-blueprint-spec",
    "test/button/button-spec",
    "test/dynamic-element/dynamic-element-spec",
    "test/input-checkbox/input-checkbox-spec",
    "test/input-number/input-number-spec",
    "test/input-radio/input-radio-spec",
    "test/input-range/input-range-spec",
    "test/input-text/input-text-spec",
    "test/list/list-spec",
    "test/popup/popup-spec",
    "test/rich-text-editor/rich-text-editor-spec",
    "test/scroller/scroller-spec",
    "test/select/select-spec",
    "test/text-slider/text-slider-spec",
    "test/toggle-button/toggle-button-spec",
    "test/token-field/token-field-spec",
    "test/video-player/video-player-spec"
]);
